const puppeteer = require("puppeteer");
const path = require("path");
const fs = require("fs");
const { ensureChrome } = require("../utils/ensureChrome");

const currencySymbols = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  AED: "د.إ",
  SAR: "ر.س",
  TRY: "₺",
  EGP: "ج.م",
};

const formatDate = (date, includeTime = false) => {
  if (!date) return "N/A";
  const options = includeTime
    ? { dateStyle: "medium", timeStyle: "short" }
    : { dateStyle: "medium" };
  return new Date(date).toLocaleString("en-US", options);
};

const sanitize = (text) => {
  if (!text) return "N/A";
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
};

class PaymentReceiptService {
  static async generatePaymentReceipt(payment, requestedBy) {
    let browser;
    try {
      await ensureChrome();

      const launchOptions = {
        headless: "new",
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-accelerated-2d-canvas",
          "--disable-gpu",
        ],
        timeout: 180000,
      };

      try {
        browser = await puppeteer.launch(launchOptions);
      } catch (error) {
        browser = await puppeteer.launch({
          headless: "new",
          args: ["--no-sandbox", "--disable-setuid-sandbox"],
        });
      }

      const page = await browser.newPage();
      const html = this.getReceiptHtml(payment, requestedBy);

      await page.setContent(html, {
        waitUntil: ["domcontentloaded", "networkidle2"],
        timeout: 90000,
      });

      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: {
          top: "1cm",
          bottom: "1.2cm",
          left: "1.2cm",
          right: "1.2cm",
        },
        displayHeaderFooter: true,
        headerTemplate: `
          <div style="font-size: 10px; color: #0f172a; width: 100%; text-align: center;">
            Rahalatek Travel • Payment Receipt
          </div>
        `,
        footerTemplate: `
          <div style="font-size: 9px; color: #64748b; width: 100%; text-align: center;">
            Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `,
      });

      return pdfBuffer;
    } finally {
      if (browser) {
        try {
          await browser.close();
        } catch (error) {
          console.error("Failed to close puppeteer browser:", error);
        }
      }
    }
  }

  static getReceiptHtml(payment, requestedBy) {
    const symbol = currencySymbols[payment.currency] || payment.currency;

    const logoPath = path.join(__dirname, "../../client/dist/Logolight.png");
    let logoBase64 = "";
    try {
      if (fs.existsSync(logoPath)) {
        const logoBuffer = fs.readFileSync(logoPath);
        logoBase64 = `data:image/png;base64,${logoBuffer.toString("base64")}`;
      }
    } catch (error) {
      console.error("Failed to load logo for payment receipt:", error);
    }

    const voucherInfo = payment.relatedVoucher
      ? `#${payment.relatedVoucher.voucherNumber} • ${sanitize(
          payment.relatedVoucher.clientName
        )}`
      : "Not linked";

    const officeDisplay = sanitize(payment.officeName || "Office");
    const counterpartyLabel =
      payment.type === "INCOMING"
        ? `From ${officeDisplay}`
        : `To ${officeDisplay}`;
    const directionLabel =
      payment.type === "INCOMING" ? "Funds Received" : "Funds Disbursed";
    const rawNotes = payment.notes || "";
    const sanitizedNotes = sanitize(rawNotes);
    const shouldHideAutoNote =
      payment.autoGenerated &&
      rawNotes.toLowerCase().includes("auto-generated");
    const notesContent =
      sanitizedNotes && !shouldHideAutoNote
        ? sanitizedNotes
        : "No additional notes provided.";

    return `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Payment Receipt - ${sanitize(payment.officeName)}</title>
    <style>
      * { box-sizing: border-box; }
      body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        margin: 0;
        padding: 24px;
        color: #0f172a;
        background: #ffffff;
      }
      .watermark {
        position: fixed;
        top: 40%;
        left: 50%;
        transform: translate(-50%, -50%);
        opacity: 0.08;
        width: 400px;
        height: auto;
        pointer-events: none;
        z-index: -1;
      }
      .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 24px;
      }
      .logo {
        display: flex;
        align-items: center;
        gap: 12px;
      }
      .logo img {
        height: 48px;
      }
      .title {
        font-size: 28px;
        font-weight: 700;
        color: #0f172a;
      }
      .badge-group {
        display: flex;
        gap: 8px;
      }
      .badge {
        padding: 6px 14px;
        border-radius: 999px;
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 0.4px;
        text-transform: uppercase;
      }
      .badge-green {
        background: #dcfce7;
        color: #15803d;
      }
      .badge-blue {
        background: #dbeafe;
        color: #1d4ed8;
      }
      .amount-display {
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 16px;
        margin-top: 16px;
        background: rgba(248, 250, 252, 0.5);
      }
      .amount-value {
        font-size: 28px;
        font-weight: 700;
        margin: 0;
        color: #0f172a;
      }
      .amount-label {
        margin-top: 6px;
        font-size: 11px;
        letter-spacing: 0.5px;
        text-transform: uppercase;
        color: #94a3b8;
      }
      .amount-direction {
        margin-top: 4px;
        font-size: 12px;
        color: #1e293b;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 18px;
        margin-bottom: 24px;
      }
      .info-card {
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 16px;
        background: rgba(248, 250, 252, 0.5);
      }
      .info-label {
        font-size: 12px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: #94a3b8;
        margin-bottom: 6px;
      }
      .info-value {
        font-size: 16px;
        font-weight: 600;
        color: #0f172a;
      }
      .section-title {
        font-size: 16px;
        font-weight: 700;
        color: #0f172a;
        margin: 0 0 12px;
        text-transform: uppercase;
        letter-spacing: 0.8px;
      }
      .notes {
        border: 1px dashed #94a3b8;
        border-radius: 12px;
        padding: 16px;
        background: rgba(248, 250, 252, 0.3);
        margin-bottom: 24px;
        min-height: 80px;
      }
      .notes p {
        margin: 0;
        color: #334155;
        line-height: 1.6;
      }
      table {
        width: 100%;
        border-collapse: collapse;
      }
      th, td {
        padding: 10px 6px;
        border-bottom: 1px solid #e2e8f0;
        font-size: 13px;
        text-align: left;
      }
      th {
        text-transform: uppercase;
        letter-spacing: 0.5px;
        font-size: 11px;
        color: #94a3b8;
      }
      .footer {
        margin-top: 24px;
        font-size: 12px;
        color: #94a3b8;
        text-align: center;
      }
    </style>
  </head>
  <body>
    ${
      logoBase64
        ? `<img src="${logoBase64}" class="watermark" alt="Watermark" />`
        : ""
    }

    <div class="card">
      <div class="header">
        <div class="logo">
          ${
            logoBase64 ? `<img src="${logoBase64}" alt="Rahalatek Logo" />` : ""
          }
          <div>
            <div class="title">Payment Receipt</div>
            <div style="color:#64748b;">Receipt ID: ${payment._id}</div>
          </div>
        </div>
        <div class="badge-group">
          <div class="badge badge-green">${payment.status.toUpperCase()}</div>
        </div>
      </div>

      <div class="grid">
        <div class="info-card">
          <div class="info-label">Office Name</div>
          <div class="info-value">${officeDisplay}</div>
        </div>
        <div class="info-card">
          <div class="info-label">Linked Voucher</div>
          <div class="info-value">${voucherInfo}</div>
        </div>
        <div class="info-card">
          <div class="info-label">Created On</div>
          <div class="info-value">${formatDate(payment.createdAt, true)}</div>
        </div>
        <div class="info-card">
          <div class="info-label">Issued By</div>
          <div class="info-value">${sanitize(
            requestedBy?.name || requestedBy?.username || "Rahalatek User"
          )}</div>
        </div>
      </div>

      <div>
        <h3 class="section-title">Notes</h3>
        <div class="notes">
          <p>${notesContent}</p>
        </div>
      </div>

      <div>
        <h3 class="section-title">Payment Timeline</h3>
        <table>
          <thead>
            <tr>
              <th>Event</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Payment Created</td>
              <td>${formatDate(payment.createdAt, true)}</td>
            </tr>
            <tr>
              <td>Payment Approved</td>
              <td>${formatDate(payment.approvedAt, true)}</td>
            </tr>
            <tr>
              <td>Payment Date</td>
              <td>${
                payment.paymentDate
                  ? formatDate(payment.paymentDate)
                  : "Not provided"
              }</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="amount-display">
        <div class="amount-label">${directionLabel}</div>
        <div class="amount-value">
          ${symbol}${payment.amount.toFixed(2)}
        </div>
        <div class="amount-direction">
          ${counterpartyLabel} • Currency: ${payment.currency}
        </div>
      </div>

      <div class="footer">
        Generated on ${formatDate(new Date(), true)} • Rahalatek Travel
      </div>
    </div>
  </body>
</html>
    `;
  }
}

module.exports = PaymentReceiptService;
