// Country codes with flags for the phone number selector
export const countryCodes = [
  { value: '+1', label: '🇺🇸 +1 (United States)' },
  { value: '+1', label: '🇨🇦 +1 (Canada)' },
  { value: '+44', label: '🇬🇧 +44 (United Kingdom)' },
  { value: '+33', label: '🇫🇷 +33 (France)' },
  { value: '+49', label: '🇩🇪 +49 (Germany)' },
  { value: '+39', label: '🇮🇹 +39 (Italy)' },
  { value: '+34', label: '🇪🇸 +34 (Spain)' },
  { value: '+31', label: '🇳🇱 +31 (Netherlands)' },
  { value: '+32', label: '🇧🇪 +32 (Belgium)' },
  { value: '+41', label: '🇨🇭 +41 (Switzerland)' },
  { value: '+43', label: '🇦🇹 +43 (Austria)' },
  { value: '+47', label: '🇳🇴 +47 (Norway)' },
  { value: '+46', label: '🇸🇪 +46 (Sweden)' },
  { value: '+45', label: '🇩🇰 +45 (Denmark)' },
  { value: '+358', label: '🇫🇮 +358 (Finland)' },
  { value: '+48', label: '🇵🇱 +48 (Poland)' },
  { value: '+420', label: '🇨🇿 +420 (Czech Republic)' },
  { value: '+36', label: '🇭🇺 +36 (Hungary)' },
  { value: '+40', label: '🇷🇴 +40 (Romania)' },
  { value: '+359', label: '🇧🇬 +359 (Bulgaria)' },
  { value: '+30', label: '🇬🇷 +30 (Greece)' },
  { value: '+90', label: '🇹🇷 +90 (Turkey)' },
  { value: '+7', label: '🇷🇺 +7 (Russia)' },
  { value: '+380', label: '🇺🇦 +380 (Ukraine)' },
  { value: '+351', label: '🇵🇹 +351 (Portugal)' },
  { value: '+353', label: '🇮🇪 +353 (Ireland)' },
  { value: '+372', label: '🇪🇪 +372 (Estonia)' },
  { value: '+371', label: '🇱🇻 +371 (Latvia)' },
  { value: '+370', label: '🇱🇹 +370 (Lithuania)' },
  { value: '+385', label: '🇭🇷 +385 (Croatia)' },
  { value: '+381', label: '🇷🇸 +381 (Serbia)' },
  { value: '+386', label: '🇸🇮 +386 (Slovenia)' },
  { value: '+387', label: '🇧🇦 +387 (Bosnia and Herzegovina)' },
  { value: '+389', label: '🇲🇰 +389 (North Macedonia)' },
  { value: '+382', label: '🇲🇪 +382 (Montenegro)' },
  { value: '+383', label: '🇽🇰 +383 (Kosovo)' },
  { value: '+355', label: '🇦🇱 +355 (Albania)' },
  { value: '+52', label: '🇲🇽 +52 (Mexico)' },
  { value: '+55', label: '🇧🇷 +55 (Brazil)' },
  { value: '+54', label: '🇦🇷 +54 (Argentina)' },
  { value: '+56', label: '🇨🇱 +56 (Chile)' },
  { value: '+57', label: '🇨🇴 +57 (Colombia)' },
  { value: '+51', label: '🇵🇪 +51 (Peru)' },
  { value: '+58', label: '🇻🇪 +58 (Venezuela)' },
  { value: '+593', label: '🇪🇨 +593 (Ecuador)' },
  { value: '+591', label: '🇧🇴 +591 (Bolivia)' },
  { value: '+595', label: '🇵🇾 +595 (Paraguay)' },
  { value: '+598', label: '🇺🇾 +598 (Uruguay)' },
  { value: '+81', label: '🇯🇵 +81 (Japan)' },
  { value: '+82', label: '🇰🇷 +82 (South Korea)' },
  { value: '+86', label: '🇨🇳 +86 (China)' },
  { value: '+852', label: '🇭🇰 +852 (Hong Kong)' },
  { value: '+853', label: '🇲🇴 +853 (Macau)' },
  { value: '+886', label: '🇹🇼 +886 (Taiwan)' },
  { value: '+65', label: '🇸🇬 +65 (Singapore)' },
  { value: '+60', label: '🇲🇾 +60 (Malaysia)' },
  { value: '+66', label: '🇹🇭 +66 (Thailand)' },
  { value: '+84', label: '🇻🇳 +84 (Vietnam)' },
  { value: '+62', label: '🇮🇩 +62 (Indonesia)' },
  { value: '+63', label: '🇵🇭 +63 (Philippines)' },
  { value: '+91', label: '🇮🇳 +91 (India)' },
  { value: '+92', label: '🇵🇰 +92 (Pakistan)' },
  { value: '+880', label: '🇧🇩 +880 (Bangladesh)' },
  { value: '+94', label: '🇱🇰 +94 (Sri Lanka)' },
  { value: '+977', label: '🇳🇵 +977 (Nepal)' },
  { value: '+975', label: '🇧🇹 +975 (Bhutan)' },
  { value: '+98', label: '🇮🇷 +98 (Iran)' },
  { value: '+964', label: '🇮🇶 +964 (Iraq)' },
  { value: '+962', label: '🇯🇴 +962 (Jordan)' },
  { value: '+961', label: '🇱🇧 +961 (Lebanon)' },
  { value: '+963', label: '🇸🇾 +963 (Syria)' },
  { value: '+970', label: '🇵🇸 +970 (Palestine)' },
  { value: '+972', label: '🇮🇱 +972 (Israel)' },
  { value: '+966', label: '🇸🇦 +966 (Saudi Arabia)' },
  { value: '+971', label: '🇦🇪 +971 (UAE)' },
  { value: '+974', label: '🇶🇦 +974 (Qatar)' },
  { value: '+965', label: '🇰🇼 +965 (Kuwait)' },
  { value: '+973', label: '🇧🇭 +973 (Bahrain)' },
  { value: '+968', label: '🇴🇲 +968 (Oman)' },
  { value: '+967', label: '🇾🇪 +967 (Yemen)' },
  { value: '+20', label: '🇪🇬 +20 (Egypt)' },
  { value: '+27', label: '🇿🇦 +27 (South Africa)' },
  { value: '+234', label: '🇳🇬 +234 (Nigeria)' },
  { value: '+254', label: '🇰🇪 +254 (Kenya)' },
  { value: '+256', label: '🇺🇬 +256 (Uganda)' },
  { value: '+255', label: '🇹🇿 +255 (Tanzania)' },
  { value: '+251', label: '🇪🇹 +251 (Ethiopia)' },
  { value: '+233', label: '🇬🇭 +233 (Ghana)' },
  { value: '+212', label: '🇲🇦 +212 (Morocco)' },
  { value: '+213', label: '🇩🇿 +213 (Algeria)' },
  { value: '+216', label: '🇹🇳 +216 (Tunisia)' },
  { value: '+218', label: '🇱🇾 +218 (Libya)' },
  { value: '+249', label: '🇸🇩 +249 (Sudan)' },
  { value: '+61', label: '🇦🇺 +61 (Australia)' },
  { value: '+64', label: '🇳🇿 +64 (New Zealand)' }
];

// Get display text for a country code
export const getCountryCodeDisplay = (code) => {
  const country = countryCodes.find(c => c.value === code);
  return country ? country.label : code;
};

// Get just the code without the country name for compact display
export const getCountryCodeShort = (code) => {
  const country = countryCodes.find(c => c.value === code);
  if (!country) return code;
  
  // Extract flag and code from label (e.g. "🇺🇸 +1" from "🇺🇸 +1 (United States)")
  const parts = country.label.split(' ');
  return `${parts[0]} ${parts[1]}`;
};
